version: "3"

services:
  api-quick-count:
    image: api-quick-count:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api-quick-count
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qc.rule=Host(`api.quick-count.techcode.cloud`)"
      - "traefik.http.routers.qc.entrypoints=web"
      - "traefik.http.services.qc.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_webgateway"
    networks:
      - traefik_webgateway

networks:
  traefik_webgateway:
    external: true
