version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quick_count
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  myapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
