// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/centrifugal/centrifuge"
	"github.com/crunchy89/api-quick-count/app/http"
	"github.com/crunchy89/api-quick-count/app/middleware"
	"github.com/crunchy89/api-quick-count/app/repository"
	"github.com/crunchy89/api-quick-count/app/routes"
	"github.com/crunchy89/api-quick-count/app/service"
	"github.com/crunchy89/api-quick-count/utils/jwt"
	"github.com/labstack/echo/v4"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitV1Routes(socket *centrifuge.Node, db *gorm.DB, logger *logrus.Entry, echo2 *echo.Echo) routes.V1Routes {
	jwtHelper := jwt.NewJWTService()
	initMiddleware := middleware.NewInitMiddleware(jwtHelper)
	roleRepository := repository.NewRoleRepository(db)
	roleService := service.NewRoleService(roleRepository, socket)
	roleHandler := http.NewRoleHandler(roleService)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(roleRepository, userRepository, socket, jwtHelper)
	authHandler := http.NewAuthHandler(userService)
	v1Routes := routes.NewV1Routes(echo2, initMiddleware, roleHandler, authHandler)
	return v1Routes
}
