name: Build And Deploy VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      
      - name: Check SSH connection to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }} 'echo "Connection successful"'
      
      - name: Create .env file
        run: |
          touch .env
          echo ENVIRONMENT=production
          echo MYSQL_DB_HOST="${{ secrets.MYSQL_DB_HOST }}"
          echo JWT_SECRET_KEY={{ secrets.JWT_SECRET_KEY }}
          echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          echo TEMP=temp
      
      - name: Build Docker image
        run: |
          docker build -t api-quick-count:latest .
          docker save -o api-quick-count.tar api-quick-count:latest

      - name: Stoping Service
        run: |
          ssh ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }} 'cd ${{ secrets.VPS_PATH_KEY }} && docker-compose down'

      - name: Transfer Docker image to VPS
        run: |
          scp api-quick-count.tar ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }}:${{ secrets.VPS_PATH_KEY }}

      - name: Run Docker Compose
        run: |
          ssh ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }} 'cd ${{ secrets.VPS_PATH_KEY }} && docker-compose up -d --build'