name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - name: Create .env file
        run: |
          touch .env
          echo ENVIRONMENT=production
          echo MYSQL_DB_HOST="${{ secrets.MYSQL_DB_HOST }}"
          echo JWT_SECRET_KEY={{ secrets.JWT_SECRET_KEY }}
          echo TEMP=temp


      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker save -o myapp.tar myapp:latest

      - name: Transfer Docker image to VPS
        run: |
          scp myapp.tar ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }}:~/code/tar/

      - name: Load Docker image on VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }} 'docker load -i ~/code/tar/myapp.tar'

      - name: Deploy using Docker Compose
        run: |
          ssh ${{ secrets.VPS_USERNAME_KEY }}@${{ secrets.VPS_IP_KEY }} 'cd ~/code/tar && docker-compose up -d --build'
