name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker save -o myapp.tar myapp:latest

      - name: Transfer Docker image to VPS
        run: |
          scp myapp.tar user@<VPS_IP>:~/path/to/destination

      - name: Load Docker image on VPS
        run: |
          ssh user@<VPS_IP> 'docker load -i ~/path/to/destination/myapp.tar'

      - name: Deploy using Docker Compose
        run: |
          ssh user@<VPS_IP> 'cd ~/path/to/destination && docker-compose up -d'
